Task/rfr 57 fix case sensitive login
cyface-de/data-collector pull request #151
Opened 2022-09-28 14:24 UTC by hb0

This PR ensures the login attempts don't fail due to case-sensitive usernames (usually an email address).

2022-09-28 14:24 UTC, hb0 commented on build.gradle
> +  cyfaceApiVersion = '2.0.1-beta1'
TODO

2022-10-04 09:17 UTC, muthenberg requested changes
Since I already completely rewrote this code, I would appreciate if you could reduce the changes to the bare necessary minimum, since all of these will result in conflicts I need to resolve. So please do not rename any variables or change methode visibilities and the like.

2022-10-04 10:14 UTC, hb0 commented
> Since I already completely rewrote this code, I would appreciate if you could reduce the changes to the bare necessary minimum, since all of these will result in conflicts I need to resolve. So please do not rename any variables or change methode visibilities and the like.

I undid the unnecessary changes

2022-10-04 13:58 UTC, muthenberg requested changes
see my comment

2022-10-04 13:58 UTC, muthenberg commented on src/main/kotlin/de/cyface/collector/handler/MeasurementHandler.kt
> -                handleFirstChunkUpload(ctx, request, session, loggedInUser, contentRange, metaData, null)
Please keep loggedInUser here. I already changed this in my pending commit.

2022-10-04 17:30 UTC, merged